// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isduljdnrbspiqsgvkiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZHVsamRucmJzcGlxc2d2a2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTkwNzQsImV4cCI6MjA2OTE3NTA3NH0.95m_dYb_tfeFNOcxyn1Sq8IQlnuTAJWvUNd2XaB85Lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});